
services:
  redis:
    image: redis:7
    ports: ["6379:6379"]
    command: ["redis-server", "--save", "", "--appendonly", "no"]

  postgres:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: brahminet
    ports: ["5432:5432"]
    volumes:
      - brahminet_pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    ports: ["9000:9000"]
    volumes:
      - brahminet_minio_data:/data

volumes:
  brahminet_pgdata:
  brahminet_minio_data:
